---
abstract: 'Light and fast ML generator'
author:
  - 'Brian West <brian@signalwire.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.1002, CPAN::Meta::Converter version 2.150005'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: SignalWire-ML
no_index:
  directory:
    - t
    - inc
requires: {}
version: '1.01'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
