---
abstract: "Accessing SignalWire's REST API with Perl"
author:
  - 'Scott Wiersdorf <scott@perlcode.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.1002, CPAN::Meta::Converter version 2.150005'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: SignalWire-RestAPI
no_index:
  directory:
    - t
    - inc
requires:
  LWP::Protocol::https: '0'
  LWP::UserAgent: '2.03'
  List::Util: '1.29'
  URI::Escape: '3.28'
version: '1.2'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
