#!/usr/bin/env python3
"""Generate the typed SWAIG read-side payload surface for signalwire-perl.

Perl realization of SESSION_CHANGESET_FOR_PORTS.md item D1 — the three
``signalwire.core.*_generated`` SWAIG payload modules — mirroring python's
``generate_swaig_request`` / ``generate_post_prompt`` / ``generate_swaig_actions``,
go's ``pkg/swaig/*_generated.go``, TS's SwaigContracts and php's
``generate_swaig_payloads.py``.

Source: the vendored porting-sdk ``swaig-specs/*.yaml`` (VENDORED from mod_openai —
the authoritative SWAIG wire spec):

  * ``swaig-request.yaml``  -> signalwire.core.swaig_request_generated  (2 classes)
        SwaigRequest (+ the inline ``argument`` object lifted to SwaigArgument).
  * ``post-prompt.yaml``    -> signalwire.core.post_prompt_generated    (14 classes)
        one class per components/schemas OBJECT schema; the ``PostPromptCallLogEntry``
        oneOf alias is NOT surfaced (the reference records it as a module-level
        TypeAlias its enumerator drops), so 15 schemas - 1 alias = 14.
  * ``swaig-response.yaml`` -> signalwire.core.swaig_actions_generated  (4 classes)
        one ``<Action>`` class per action key whose value is an object-with-properties
        (a bare object OR an object variant of a oneOf): context_switch ->
        ContextSwitchAction, hold -> HoldAction, playback_bg -> PlaybackBgAction,
        transfer -> TransferAction. The ``SwaigResponse``/``SwaigAction`` envelope
        schemas + the ergonomic ``_SwaigActions`` method surface are NOT part of the
        cross-port surface oracle, so only the 4 object-shaped action value classes.

  2 + 14 + 4 = 20 classes == the surface oracle EXACTLY (0 missing / 0 extra).

Every emitted class is a method-less Moo data DTO: one read-only ``has`` accessor per
property carrying the snake wire key, no methods. The emit/drop rule reuses the SHARED
helpers from generate_rest.py (is_object_schema, type_name, perl_attr_name) exactly
like generate_swml_verbs.py / generate_relay_protocol.py.

These are READ-side payloads (open shapes; no ``extras`` door). The signature
enumerator emits each ``has`` property as a zero-arg member and the diff tool's
gen-payload fold canonicalizes the module, so a class-typed field
(PostPrompt.call_log, SwaigRequest.argument, …) compares by (class, field).

Output layout: one class per file under a per-module subdir
  lib/SignalWire/SWAIG/Generated/PostPrompt/<ClassName>.pm
  lib/SignalWire/SWAIG/Generated/SwaigRequest/<ClassName>.pm
  lib/SignalWire/SWAIG/Generated/SwaigActions/<ClassName>.pm
so the surface + signature enumerators route each subdir BY PATH to its
``signalwire.core.<post_prompt|swaig_request|swaig_actions>_generated`` oracle module
(winning over the package map so the hand-written SWAIG SDK classes — FunctionResult,
ParameterSchema — are never misrouted).

Usage:
    python3 scripts/generate_swaig_payloads.py            # write into the repo tree
    python3 scripts/generate_swaig_payloads.py --check    # GEN-FRESH: fail if stale
    python3 scripts/generate_swaig_payloads.py --out DIR  # scratch: emit into DIR
"""
from __future__ import annotations

import argparse
import importlib.util
import re
import sys
from pathlib import Path


# ---------------------------------------------------------------------------
# Reuse the shared emit helpers from generate_rest.py. Import by path so the
# generators never diverge on the emit rule.
# ---------------------------------------------------------------------------

def _load_rest_generator():
    here = Path(__file__).resolve().parent
    spec = importlib.util.spec_from_file_location("generate_rest", here / "generate_rest.py")
    if spec is None or spec.loader is None:  # pragma: no cover
        raise SystemExit("generate_swaig_payloads.py: cannot load generate_rest.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


GR = _load_rest_generator()


def resolve_porting_sdk() -> Path:
    return GR.resolve_porting_sdk()


def repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def _load_yaml(path: Path) -> dict:
    import yaml  # type: ignore[import-untyped]

    return yaml.safe_load(path.read_text())


# ---------------------------------------------------------------------------
# Emit.
# ---------------------------------------------------------------------------

SWAIG_HEADER = (
    "# Code generated by scripts/generate_swaig_payloads.py; DO NOT EDIT.\n"
    "#\n"
    "# AUTO-GENERATED from porting-sdk/swaig-specs/{spec} — regenerate with:\n"
    "#   python3 scripts/generate_swaig_payloads.py\n"
    "#\n"
    "# {desc}\n"
)


def _emit_class(pl_name: str, properties: dict, spec: str, sub: str, source_desc: str) -> str:
    """Emit one method-less Moo data package for a SWAIG payload object schema."""
    pkg = f"SignalWire::SWAIG::Generated::{sub}::{pl_name}"
    desc = f"Generated SWAIG payload wire type {pl_name!r} ({source_desc})."
    out = SWAIG_HEADER.format(spec=spec, desc=desc)
    out += f"package {pkg};\n"
    out += "use strict;\n"
    out += "use warnings;\n"
    out += "use Moo;\n\n"
    out += "# Pure data DTO: one read-only accessor per property carrying the snake\n"
    out += "# wire key; no methods (the reference records this as a method-less type).\n"
    used: set[str] = set()
    for wire_key in properties:
        attr = GR.perl_attr_name(wire_key)
        while attr in used:
            attr += "_"
        used.add(attr)
        if attr != wire_key:
            out += f"# wire key: {wire_key}\n"
        out += GR.perl_has_decl(attr) + "\n"
    out += "\n1;\n"
    return out


def _pascal_verb(verb: str) -> str:
    """PascalCase a snake action key: ``context_switch`` -> ``ContextSwitch``."""
    return "".join(w[:1].upper() + w[1:] for w in re.split(r"[._\-\s]", verb) if w)


# ---------------------------------------------------------------------------
# Per-spec builders. Each returns {relative_path: source} where the path is
# ``<Sub>/<Class>.pm`` (the subdir routes the enumerators to the oracle module).
# ---------------------------------------------------------------------------

def _build_swaig_request(psdk: Path) -> dict:
    """swaig-request.yaml -> SwaigRequest (+ lifted SwaigArgument)."""
    spec_file = "swaig-request.yaml"
    sub = "SwaigRequest"
    spec = _load_yaml(psdk / "swaig-specs" / spec_file)
    schema = spec["components"]["schemas"]["SwaigRequest"]
    props = schema.get("properties", {})

    outs: dict = {}
    arg = props.get("argument")
    if isinstance(arg, dict) and arg.get("properties"):
        outs[f"{sub}/SwaigArgument.pm"] = _emit_class(
            "SwaigArgument", arg["properties"], spec_file, sub,
            "inline swaig-request `argument` object")
    outs[f"{sub}/SwaigRequest.pm"] = _emit_class(
        "SwaigRequest", props, spec_file, sub, "swaig-request `SwaigRequest` schema")
    return outs


def _build_post_prompt(psdk: Path) -> dict:
    """post-prompt.yaml -> one class per components/schemas OBJECT schema (15-1=14)."""
    spec_file = "post-prompt.yaml"
    sub = "PostPrompt"
    spec = _load_yaml(psdk / "swaig-specs" / spec_file)
    schemas = spec["components"]["schemas"]

    outs: dict = {}
    emitted: set = set()
    for raw_name, node in schemas.items():
        if not isinstance(node, dict):
            continue
        if not GR.is_object_schema(node):
            continue
        pl_name = GR.type_name(raw_name)
        if pl_name in emitted:
            continue
        emitted.add(pl_name)
        outs[f"{sub}/{pl_name}.pm"] = _emit_class(
            pl_name, node.get("properties") or {}, spec_file, sub,
            f"post-prompt components/schemas {raw_name!r}")
    return outs


def _build_swaig_actions(psdk: Path) -> dict:
    """swaig-response.yaml -> one <Action> class per action key whose value is an
    object-with-properties (a bare object OR the object variant(s) of a oneOf)."""
    spec_file = "swaig-response.yaml"
    sub = "SwaigActions"
    spec = _load_yaml(psdk / "swaig-specs" / spec_file)
    actions = spec["components"]["schemas"]["SwaigAction"]["properties"]

    def _is_obj(s) -> bool:
        return isinstance(s, dict) and s.get("type") == "object" and bool(s.get("properties"))

    outs: dict = {}
    emitted: set = set()
    for verb in sorted(actions):
        schema = actions[verb]
        if not isinstance(schema, dict):
            continue
        branches = schema.get("oneOf") or ([schema] if _is_obj(schema) else [])
        obj_i = 0
        for b in branches:
            if not _is_obj(b):
                continue
            obj_i += 1
            action_name = _pascal_verb(verb) + "Action" + ("" if obj_i == 1 else str(obj_i))
            pl_name = GR.type_name(action_name)
            if pl_name in emitted:
                continue
            emitted.add(pl_name)
            outs[f"{sub}/{pl_name}.pm"] = _emit_class(
                pl_name, b.get("properties") or {}, spec_file, sub,
                f"swaig-response action {verb!r} value object")
    return outs


def build_outputs(psdk: Path) -> dict:
    specs_dir = psdk / "swaig-specs"
    if not specs_dir.is_dir():
        raise SystemExit(
            f"generate_swaig_payloads.py: {specs_dir} not found (need porting-sdk adjacency)"
        )
    outs: dict = {}
    outs.update(_build_post_prompt(psdk))
    outs.update(_build_swaig_request(psdk))
    outs.update(_build_swaig_actions(psdk))
    return outs


# ---------------------------------------------------------------------------
# Driver.
# ---------------------------------------------------------------------------

def main(argv) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="GEN-FRESH: exit non-zero if stale")
    ap.add_argument("--out", default="", help="scratch: emit into this dir")
    args = ap.parse_args(argv)

    psdk = resolve_porting_sdk()
    outs = build_outputs(psdk)

    if args.out:
        out_dir = Path(args.out)
    else:
        out_dir = repo_root() / "lib" / "SignalWire" / "SWAIG" / "Generated"

    if args.check:
        stale: list = []
        for fn, src in outs.items():
            p = out_dir / fn
            if not p.is_file() or p.read_text() != src:
                stale.append(str(p))
        expected = set(outs.keys())
        if out_dir.is_dir():
            for p in sorted(out_dir.rglob("*.pm")):
                rel = p.relative_to(out_dir).as_posix()
                if rel not in expected:
                    stale.append(f"{p} (leftover — not in generator output)")
        if stale:
            sys.stderr.write("GEN-FRESH FAIL: %d generated SWAIG-payload file(s) stale:\n" % len(stale))
            for s in stale:
                sys.stderr.write("  - %s\n" % s)
            return 1
        print("GEN-FRESH: generated SWAIG-payload files match porting-sdk/swaig-specs/*.yaml.")
        return 0

    out_dir.mkdir(parents=True, exist_ok=True)
    for fn, src in outs.items():
        p = out_dir / fn
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(src)
    print(f"generated {len(outs)} SWAIG-payload file(s) into {out_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
